In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import sys, os
sys.path.append(os.path.abspath('..'))
from src.data import get_data
from src.ml import *
from src.evaluate import evaluate_model
from src.optimization import *

c:\Users\YOGA\Desktop\01_Time Series\PROJECT\Github\Electricity-Load-Diagrams\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df_clean = get_data('df_clean')
df_clean.head()

Đã đọc thành công dữ liệu từ: C:\Users\YOGA\Desktop\01_Time Series\PROJECT\Github\Electricity-Load-Diagrams\data\processed\df_clean

,total_load,hour,quarter,month,day_of_week,day_of_month,day_of_year,week_of_year,is_weekend,hour_sin,hour_cos,day_sin,day_cos,quarter_sin,quarter_cos,year_sin,year_cos,holiday_name
Timestamp,,,,,,,,,,,,,,,,,,
2011-01-01 00:00:00,51764.567568,0,1,1,5,1,1,52,1,0.000000,1.000000,-0.974928,-0.222521,0.0,1.0,0.0,1.0,Ano Novo
2011-01-01 01:00:00,66344.627687,1,1,1,5,1,1,52,1,0.258819,0.965926,-0.974928,-0.222521,0.0,1.0,0.0,1.0,Ano Novo
2011-01-01 02:00:00,65981.054883,2,1,1,5,1,1,52,1,0.500000,0.866025,-0.974928,-0.222521,0.0,1.0,0.0,1.0,Ano Novo
2011-01-01 03:00:00,66576.533566,3,1,1,5,1,1,52,1,0.707107,0.707107,-0.974928,-0.222521,0.0,1.0,0.0,1.0,Ano Novo
2011-01-01 04:00:00,64963.552675,4,1,1,5,1,1,52,1,0.866025,0.500000,-0.974928,-0.222521,0.0,1.0,0.0,1.0,Ano Novo

In [3]:
df_all = get_data('df_all_features')
df_all.head()

Đã đọc thành công dữ liệu từ: C:\Users\YOGA\Desktop\01_Time Series\PROJECT\Github\Electricity-Load-Diagrams\data\processed\df_all_features

,total_load,hour,quarter,month,day_of_week,day_of_month,day_of_year,week_of_year,is_weekend,hour_sin,...,year_sin,year_cos,holiday_name,lag_1y_base,rolling_mean_1y_day,rolling_std_1y_day,rolling_mean_1y_week,rolling_std_1y_week,rolling_mean_1y_month,rolling_std_1y_month
Timestamp,,,,,,,,,,,,,,,,,,,,,
2012-01-28 00:00:00,140768.241446,0,1,1,5,28,28,4,1,0.000000,...,0.447945,0.894061,None,143212.263509,188788.092565,54389.326319,187266.945729,53105.476645,186376.645512,54187.677460
2012-01-28 01:00:00,117639.433304,1,1,1,5,28,28,4,1,0.258819,...,0.447945,0.894061,None,120764.721437,188955.307388,54163.929741,187249.743349,53126.669698,186385.515110,54176.431477
2012-01-28 02:00:00,111940.451150,2,1,1,5,28,28,4,1,0.500000,...,0.447945,0.894061,None,112877.467842,189006.011645,54088.943829,187235.294743,53146.679685,186387.552790,54173.636676
2012-01-28 03:00:00,103170.529666,3,1,1,5,28,28,4,1,0.707107,...,0.447945,0.894061,None,105274.090696,188932.898109,54205.632644,187219.629055,53170.585596,186384.967558,54177.471566
2012-01-28 04:00:00,99374.780029,4,1,1,5,28,28,4,1,0.866025,...,0.447945,0.894061,None,101608.492676,188794.478583,54433.231297,187204.583784,53194.588069,186378.580911,54187.225633

In [4]:
df_best = get_data('df_best_features')
df_best.head()

Đã đọc thành công dữ liệu từ: C:\Users\YOGA\Desktop\01_Time Series\PROJECT\Github\Electricity-Load-Diagrams\data\processed\df_best_features

,hour,day_of_week,day_of_month,day_of_year,is_weekend,hour_sin,hour_cos,month_sin,month_cos,holiday_name,lag_1y_base,rolling_mean_1y_week,rolling_mean_1y_month,total_load
Timestamp,,,,,,,,,,,,,,
2012-01-28 00:00:00,0,5,28,28,1,0.000000,1.000000,0.0,1.0,None,141712.314795,186801.532764,186258.087845,140768.241446
2012-01-28 01:00:00,1,5,28,28,1,0.258819,0.965926,0.0,1.0,None,118901.037687,186781.298061,186266.526224,117639.433304
2012-01-28 02:00:00,2,5,28,28,1,0.500000,0.866025,0.0,1.0,None,110743.382074,186756.475245,186266.526315,111940.451150
2012-01-28 03:00:00,3,5,28,28,1,0.707107,0.707107,0.0,1.0,None,102809.733504,186734.366882,186258.695452,103170.529666
2012-01-28 04:00:00,4,5,28,28,1,0.866025,0.500000,0.0,1.0,None,99802.295376,186716.551836,186249.189253,99374.780029

In [6]:
from src.split import split_train_test

X_train, X_test, y_train, y_test, encoder = split_train_test(df_all, target="total_load", split_time="2014-01-01", categorical_cols=['holiday_name'])

# LightGBM

In [7]:
model, preds = lightgbm_model(X_train, y_train, X_test)
results = evaluate_model(y_test, preds)

==============================
MAE: 14745.1016
MSE: 406365911.7131
RMSE: 20158.5196
MAPE (%): 6.6326
==============================

# XGBoost

In [8]:
model, preds = xgboost_model(X_train, y_train, X_test)
results = evaluate_model(y_test, preds)

==============================
MAE: 14433.6313
MSE: 412163524.0435
RMSE: 20301.8109
MAPE (%): 6.2802
==============================

# Catboost

In [9]:
model, preds = catboost_model(X_train, y_train, X_test)
results = evaluate_model(y_test, preds)

KeyboardInterrupt: